### ISSUE TITLE
readme example appears outdated

### ISSUE THREAD

**Issue by rmriches** [korylprince/mbox#1]
The example in the readme file appears outdated.  For example, there does not appear to be a ReadMessage function.  Also, the line that calls bufio.NewReader uses variable 'r' in the same line it declares the same variable.

**Comment by korylprince** [comment]
Thanks for the heads up! I've updated the example (now in the package docs instead of the README) to work with the v1 API. Also note, the `mail.ReadMessage` is from `net/mail`. This package is for reading individual messages from an mbox file; the actual message parsing is still done by `net/mail`.
